/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class fluid {
  public static void c_densitySolver(float[] d, float[] dOld, float diff, float[] u, float[] v, float dt, int grid_size, int vector_size) {
    fluidJNI.c_densitySolver(d, dOld, diff, u, v, dt, grid_size, vector_size);
  }

  public static void c_velocitySolver(float[] u, float[] uOld, float[] v, float[] vOld, float[] curl, float[] d, float visc, float dt, int grid_size, int vector_size) {
    fluidJNI.c_velocitySolver(u, uOld, v, vOld, curl, d, visc, dt, grid_size, vector_size);
  }

}
